# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunr" do
  name "tunr"
  desc "local → public tunnel tool for Vibecoders"
  homepage "https://tunr.sh"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunr"

  on_macos do
    on_intel do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "d5baf673a89dab48b1c0feed1caa58f058801df2496de8f6a7632f6e4b899552"
    end
    on_arm do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "918cfa9b326bbf2098a21cad40c9275733b92ffd7dec8dd0c49a2bf03c78c62d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "f273fd132f8dde80884f40657967f5727457fc463dd6f73ca2133d4751c999f4"
    end
    on_arm do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "be62e4c21c6ccc419e9ebc73ec6099edfe18aea0a87008c11f2693a10b65d5f8"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunr"]
    end
  end

  # No zap stanza required
end
