# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunr" do
  name "tunr"
  desc "local → public tunnel tool for Vibecoders"
  homepage "https://tunr.sh"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunr"

  on_macos do
    on_intel do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "912380c714746cda4a888fe89b3808b69cc773b2db851bcfa62bd54bd8082cdd"
    end
    on_arm do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "ea7a49b0652082f04a2f27d4aebd5da234cbb7b10f21d3df9339359b7d87e7db"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "ad798ca6a9577d9e7225b8e8aeff1e9b50a860356fc0336c64b1f8aed31b542e"
    end
    on_arm do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "6e50ee5d0f1bd76090443c19a68e7f5086e92891104b76a6b9a83c6879b062d6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunr"]
    end
  end

  # No zap stanza required
end
