# This file was generated by GoReleaser. DO NOT EDIT.
cask "tunr" do
  name "tunr"
  desc "local → public tunnel tool for Vibecoders"
  homepage "https://tunr.sh"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tunr"

  on_macos do
    on_intel do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "943ff7661985d9289eb9597d4ef1aa502ef80bee924c43522ef59e746010990f"
    end
    on_arm do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "18761c8e64f6362b9ae5ba812c798bf3d82163b343d4f54b8484c62e4e119af2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "456ca11348bf5df59fee68d0417e8e0888390d1adac247eb9963afc7556a76ef"
    end
    on_arm do
      url "https://github.com/ahmetvural79/tunr/releases/download/v#{version}/tunr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ahmetvural79/tunr"
      sha256 "844b8ede83581b9f6c416cc678ff5ab4670666cce8ead77c2774785d9461cbf9"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tunr"]
    end
  end

  # No zap stanza required
end
